### ISSUE TITLE
Deploy script doesn't work

### ISSUE THREAD

**Issue by joryphillips** [samccone/moji-brush#23]
Expected behavior: Deploy works

Unexpected behavior: Deploy is broken

Error message:

```
fatal: remote origin already exists.

npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "deploy"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9
npm ERR! code ELIFECYCLE
npm ERR! moji-brush@1.0.0 deploy: `./deploy.sh`
npm ERR! Exit status 128
```

npm-debug.log:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'deploy' ]
2 info using npm@3.8.9
3 info using node@v6.2.0
4 verbose run-script [ 'predeploy', 'deploy', 'postdeploy' ]
5 info lifecycle moji-brush@1.0.0~predeploy: moji-brush@1.0.0
6 silly lifecycle moji-brush@1.0.0~predeploy: no script for predeploy, continuing
7 info lifecycle moji-brush@1.0.0~deploy: moji-brush@1.0.0
8 verbose lifecycle moji-brush@1.0.0~deploy: unsafe-perm in lifecycle true
9 verbose lifecycle moji-brush@1.0.0~deploy: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/joryp/Desktop/moji-brush/node_modules/.bin:/usr/local/bin:/Users/joryp/google-cloud-sdk/bin:/usr/local/git/current/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin
10 verbose lifecycle moji-brush@1.0.0~deploy: CWD: /Users/joryp/Desktop/moji-brush
11 silly lifecycle moji-brush@1.0.0~deploy: Args: [ '-c', './deploy.sh' ]
12 silly lifecycle moji-brush@1.0.0~deploy: Returned: code: 128  signal: null
13 info lifecycle moji-brush@1.0.0~deploy: Failed to exec deploy script
14 verbose stack Error: moji-brush@1.0.0 deploy: `./deploy.sh`
14 verbose stack Exit status 128
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:245:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:850:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid moji-brush@1.0.0
16 verbose cwd /Users/joryp/Desktop/moji-brush
17 error Darwin 15.5.0
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "deploy"
19 error node v6.2.0
20 error npm  v3.8.9
21 error code ELIFECYCLE
22 error moji-brush@1.0.0 deploy: `./deploy.sh`
22 error Exit status 128
23 error Failed at the moji-brush@1.0.0 deploy script './deploy.sh'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the moji-brush package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     ./deploy.sh
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs moji-brush
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls moji-brush
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]


```

**Comment by samccone** [comment]
you need to make sure your origin remote is set to `git@github.com:samccone/moji-brush.git`
and you have push permissions

**Comment by joryphillips** [comment]
Hmmmm. This is a real Scooby Doo mystery.

```
joryp-macbookpro2:moji-brush joryp$ git remote -v
joryfork    https://github.com/joryphillips/moji-brush.git (fetch)
joryfork    https://github.com/joryphillips/moji-brush.git (push)
origin  https://github.com/samccone/moji-brush.git (fetch)
origin  https://github.com/samccone/moji-brush.git (push)
joryp-macbookpro2:moji-brush joryp$ 
```

**Comment by samccone** [comment]
do you have the correct permissions to push to origin on your computer?

just try pushing a change

**Comment by joryphillips** [comment]
Check; no problem pushing to origin

**Comment by samccone** [comment]
i guess run through each of the commands in deploy.sh and see which one fails

**Comment by samccone** [comment]
oh wait, just rm -rf dist/ before you start... that should fix it ha

**Comment by joryphillips** [comment]
It was an SSH issue and I did need to rm-rf dist
